// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backas;

#nullable disable

namespace backas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backas.Fakultetas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrumpasPavadinimas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UniversitetasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversitetasId");

                    b.ToTable("Fakultetai");
                });

            modelBuilder.Entity("backas.Fotografas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Fotografai");
                });

            modelBuilder.Entity("backas.Maketuotojas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DesignUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Maketuotojai");
                });

            modelBuilder.Entity("backas.Universitetas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrumpasPavadinimas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Universitetai");
                });

            modelBuilder.Entity("backas.Vartotojai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FakultetasId")
                        .HasColumnType("int");

                    b.Property<int?>("FotografasId")
                        .HasColumnType("int");

                    b.Property<int?>("MaketuotojasId")
                        .HasColumnType("int");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrisijungimoVardas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Slaptazodis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefonas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UniversitetasId")
                        .HasColumnType("int");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VartotojoRole")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FakultetasId");

                    b.HasIndex("FotografasId");

                    b.HasIndex("MaketuotojasId");

                    b.HasIndex("UniversitetasId");

                    b.ToTable("Vartotojai");
                });

            modelBuilder.Entity("backas.Fakultetas", b =>
                {
                    b.HasOne("backas.Universitetas", "Universitetas")
                        .WithMany("Fakultetai")
                        .HasForeignKey("UniversitetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universitetas");
                });

            modelBuilder.Entity("backas.Vartotojai", b =>
                {
                    b.HasOne("backas.Fakultetas", "Fakultetas")
                        .WithMany("Vartotojai")
                        .HasForeignKey("FakultetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backas.Fotografas", "Fotografas")
                        .WithMany()
                        .HasForeignKey("FotografasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backas.Maketuotojas", "Maketuotojas")
                        .WithMany()
                        .HasForeignKey("MaketuotojasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backas.Universitetas", "Universitetas")
                        .WithMany("Vartotojai")
                        .HasForeignKey("UniversitetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakultetas");

                    b.Navigation("Fotografas");

                    b.Navigation("Maketuotojas");

                    b.Navigation("Universitetas");
                });

            modelBuilder.Entity("backas.Fakultetas", b =>
                {
                    b.Navigation("Vartotojai");
                });

            modelBuilder.Entity("backas.Universitetas", b =>
                {
                    b.Navigation("Fakultetai");

                    b.Navigation("Vartotojai");
                });
#pragma warning restore 612, 618
        }
    }
}
