// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backas;

#nullable disable

namespace backas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backas.fakultetas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrumpasPavadinimas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("universitetasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("universitetasId");

                    b.ToTable("fakultetai");
                });

            modelBuilder.Entity("backas.grupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApmokejimoStadija")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("BaigimoMetai")
                        .HasColumnType("int");

                    b.Property<bool>("BalsavimasMaketai")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("fakultetasId")
                        .HasColumnType("int");

                    b.Property<string>("FotografavimoDataVieta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GamybosStadija")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("grupesSeniunas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IlgasPavadinimas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Pasleptigrupe")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pastabos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("PatvirtintasSarasas")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StudentuSkaicius")
                        .HasColumnType("int");

                    b.Property<decimal>("SumoketasAvansas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("universitetasId")
                        .HasColumnType("int");

                    b.Property<int>("ĮstojimoMetai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("fakultetasId");

                    b.HasIndex("universitetasId");

                    b.ToTable("grupes");
                });

            modelBuilder.Entity("backas.universitetas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrumpasPavadinimas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("universitetai");
                });

            modelBuilder.Entity("backas.vartotojai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("fakultetasId")
                        .HasColumnType("int");

                    b.Property<int?>("grupeId")
                        .HasColumnType("int");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrisijungimoVardas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Slaptazodis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefonas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("universitetasId")
                        .HasColumnType("int");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VartotojoRole")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("fakultetasId");

                    b.HasIndex("grupeId");

                    b.HasIndex("universitetasId");

                    b.ToTable("vartotojai");
                });

            modelBuilder.Entity("backas.fakultetas", b =>
                {
                    b.HasOne("backas.universitetas", "universitetas")
                        .WithMany("fakultetai")
                        .HasForeignKey("universitetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("universitetas");
                });

            modelBuilder.Entity("backas.grupe", b =>
                {
                    b.HasOne("backas.fakultetas", "fakultetas")
                        .WithMany("grupes")
                        .HasForeignKey("fakultetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backas.universitetas", "universitetas")
                        .WithMany("grupes")
                        .HasForeignKey("universitetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fakultetas");

                    b.Navigation("universitetas");
                });

            modelBuilder.Entity("backas.vartotojai", b =>
                {
                    b.HasOne("backas.fakultetas", "fakultetas")
                        .WithMany("vartotojai")
                        .HasForeignKey("fakultetasId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backas.grupe", "grupe")
                        .WithMany("vartotojai")
                        .HasForeignKey("grupeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backas.universitetas", "universitetas")
                        .WithMany("vartotojai")
                        .HasForeignKey("universitetasId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("fakultetas");

                    b.Navigation("grupe");

                    b.Navigation("universitetas");
                });

            modelBuilder.Entity("backas.fakultetas", b =>
                {
                    b.Navigation("grupes");

                    b.Navigation("vartotojai");
                });

            modelBuilder.Entity("backas.grupe", b =>
                {
                    b.Navigation("vartotojai");
                });

            modelBuilder.Entity("backas.universitetas", b =>
                {
                    b.Navigation("fakultetai");

                    b.Navigation("grupes");

                    b.Navigation("vartotojai");
                });
#pragma warning restore 612, 618
        }
    }
}
